plugins: 
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: kzu/beautiful-jekyll@master
title: Analia Carvallo
author: Analia Carvallo
keywords: "coding,C#,.NET,programming"
google-search-id: 745e5e4dad17abd9b
google_analytics: G-RD1ECCM3F2
rss-description: Analia Carvallo

permalink:        /:title.html 
url:              https://anycoder.net
baseurl:          ""
disqus:           anycoder

exclude:      [ "readme.md", "license.txt", "CNAME", "Gemfile" ]
paginate:     10
port:         3000
host:         127.0.0.1

title-img: /assets/img/any.svg
avatar: /assets/img/any.jpg

social-network-links:
  alias:          anycoder
  email:         anycarvallo@gmail.com
  github:        anycarvallo
  linkedin:       AnaliaCarvallo
  stackoverflow:  15935352/AnyCarvallo
  twitter:       anycarvallo

navbar-links:
  Archive: "/archive/"
  Tags: "/tags/"

share-links-active:
  github: true
  twitter: true
  linkedin: true
  stackoverflow: true

url-pretty: "anycoder.net"
excerpt_length: 100
feed_show_tags: true
hover-col: "#FFC926"

defaults:
  -
    values:
      head-extra: favicon.html
      footer-extra: license.html